### ISSUE TITLE
UploadBio (and probably NewCC) don't handle non-UTF-8 files well

### ISSUE THREAD

**Issue by medeor413** [medeor413/Red_Star#102]

**Comment by GTG3000** [comment]
Do we include [chardet](https://pypi.python.org/pypi/chardet) or [pyicu](https://pypi.python.org/pypi/PyICU/0.8.1)?

Or do we just tell users to start using a proper text editor?

**Comment by medeor413** [comment]
I'd vote for just trying `utf-8`, `utf-8-sig`, and `windows-1252` in sequence, which should cover it pretty well

**Comment by GTG3000** [comment]
Just tested, windows-1252 decodes just fine in utf-8.
