### ISSUE TITLE
Purge storage data from servers bot is not on

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#114]
Otherwise it breaks if the bot leaves a server and then goes over storage.

**Comment by medeor413** [comment]
This is something that has to be done per-plugin; which plugins specifically break when this occurs?

**Comment by GTG3000** [comment]
It was mostly the antispam.

**Comment by medeor413** [comment]
Since that's gone, is this issue still necessary?

**Comment by GTG3000** [comment]
It's a grim reminder that your plugin shouldn't expect all the guilds still be there.

**Comment by medeor413** [comment]
Fair enough
