### ISSUE TITLE
Refactor message splitting helper functions.

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#165]
`split_output` and `split_message` do very similar tasks slightly differently, and could likely be refactored into one function that does the task of splitting a large text into message-sized chunks.

### `split_message(message_str, splitter=None, max_len=2000)`
Takes a single string and splits it into chunks up to `max_len`, attempting to split at the `splitter` character if given.

Robust and simple. Can be used to format lists into multiple messages with headers and footers with creative use of `max_len` and `splitter` parameters and some follow-up processing.

### `split_output(message, title, items, *, header="'''n", footer="'''", string_processor=lambda x: str(x) + "\n")`
Takes a `message` object and a list of `items`, from which it attempts to generate a number of output messages, complete with a `title` before the list.

Messages are formed to include given `header` and `footer`, collecting as many items in each message as can fit. Items are passed through the `string_processor` function, allowing the function to accept arbitrary lists and format them in arbitrary ways, although still only based on each item.

Is used more than the `split_message` function in the code and gives easy solution for formatting lists, but does not currently deal with individual items being bigger than message length - for example, roll command with high dice numbers will result in cut-off messages. In the same vein, while `string_processor` helps with flexibility, it does not allow for formatting akin to `", ".join(list)`.  
It may be impossible to implement something like that in a sensible manner.

## Usecase:

Most of the usage of the two functions can be attributed to outputting lists of data that may or may not fit into one message, with a leading footer of some description, usually inside a multiline code block. 

With that in mind, `split_output` may be more complex than it really needs to be, but it also deduplicates a chunk of post-processing code that would have to follow similar use of `split_message`, namely applying headers and footers.

`string_processor` optional parameter can and probably should be replaced by formatting data properly before input for clarity, even if in a list comprehension.

**Comment by medeor413** [comment]
Yeah, I'm thinking of a sort of combination of both; a function that takes a string of arbitrary length, breaks it into configurable-length pieces (usually on a specific splitting character, which will default to `\n` rather than `None`), and most importantly, properly closes formatting strings, before returning a list of strings to be sent by the caller.
