### ISSUE TITLE
Bot does not handle not having admin permissions well.

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#166]
We can't *actually* assume that the bot always has admin permissions, and most of it's functions can work pretty well without them.

### Currently known issues:

- [ ] Logger may fail when trying to access audit log, unhandled.
- [ ] Purge command has no handling for inability to delete.
- [ ] Music Plugin fails quietly when it can't connect to a channel.

Possibly more.

**Comment by GTG3000** [comment]
Added music plugin permission handling bug.

**Comment by medeor413** [comment]
Closing for now since all listed issues are fixed; reopen if necessary.
