### ISSUE TITLE
Block Red Star from operating in specific channels at users discretion

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#54]

**Comment by medeor413** [comment]
Remove `Read Channel` permission? Seems simple enough to me.

**Comment by GTG3000** [comment]
Not with admin permissions, it ain't.

**Comment by medeor413** [comment]
Then remove Administrator from the bot

**Comment by medeor413** [comment]
Probably implement this under #63, with a category that can be respected by all plugins, e.g. "nospeak" and/or "noread"

**Comment by GTG3000** [comment]
Alright, this is implemented.

**Comment by GTG3000** [comment]
Alright, this is implemented.

**Comment by medeor413** [comment]
Not quite.
