### ISSUE TITLE
Add <fancify> tag to turn text fabulous in CCs

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#56]
I'll need your fancy pants text generator code for that tho.

**Comment by medeor413** [comment]
I'd rather add a general translate tag where the user can specify which characters to translate to which (and also remove rot13).

**Comment by GTG3000** [comment]
General translate tag is not user-friendly at all, however, it can be done.
I think a tag with <trans:style:text> formatting would be more useful, unless you hate end user.

**Comment by medeor413** [comment]
I don't see anything *terribly* user-unfriendly in `<translate:text:from:to>`. If they can't figure it out it's their own damn problem

**Comment by GTG3000** [comment]
Well, 

1. Assembling a character set like that is at the very least annoying and at most - not doable for people who didn't memorize the unicode symbol tables.
2. Including this stuff into the cc, while giving customisability, takes up the length of the message.
3. Not making people do it themselves is kind of the point of adding it into a bit.

**Comment by medeor413** [comment]
I'd rather not include a bunch of tags that all produce nearly-identical results, when one tag would suffice perfectly well. If they need to translate fixed strings into different character sets, there are plenty of online tools they can use for that.

**Comment by medeor413** [comment]
> unless you hate end user.
I do, so I'm in favor of general-purpose translate tag. It's more useful in general, at the cost of less ease-of-use. If they can't figure it out, then they don't need to use it.
