### ISSUE TITLE
Commands: Underscores or no?

### ISSUE THREAD

**Issue by medeor413** [medeor413/Red_Star#99]
There's an inconsistency in a lot of our command names, which is that some use underscores to separate words, and some have no separation. We should decide on which of these to use and update everything to match. Personally, I'm a fan of the snake_case option.

**Comment by GTG3000** [comment]
I think snake_case is less organic for end users than !somewordswithoutspaces... case.

**Comment by medeor413** [comment]
I've said in the past that I don't care especially much about end users, but it is a valid point, and it does save time when typing commands... If I can figure out a way to get `help` to display the commands with appropriate capitalization, I don't see why not, I guess.

**Comment by GTG3000** [comment]
Store command names with capitalization, match command names with .lower()

**Comment by medeor413** [comment]
Most likely way, yeah. I guess we're done here, then.
